module.exports = {
	someSidebar: {
		Introduction: [
			'welcome',
			'what-is-nimbella',
			'serverless',
			'serverless-vs-server',
			'serveless-apps',
			'why-nimbella',
			'account',
			'features',
			'openwhisk',
		],
		'Nimbella Project': [
			'deployer-overview',
			'projects',
			'namespaces',
			'actions',
			'project',
			'configuration',
			'deployer-feature',
			'single-action',
			'namespace-to-projects',
		],
		'Serverless SDK': ['key-value-sdk', 'file-stores'],
		'Runtime & Languages': ['runtime'],
		CLI: ['install', 'commands', 'flags', 'command-summary', 'wsk'],
		Workbench: ['workbench'],
		'Getting Started': ['getting-started', 'building'],
		'Developing and Deploying Serverless APIs': [
			'sample-project-walkthrough',
			'stateful-api-examples',
		],
		'Developing & Deploying Web': ['web', 'web-content'],
		'Taking your application to production': ['production'],
		Integrations: ['commander', 'postman', 'netlify'],
		'Porting existing applications onto Nimbella': [
			'heroku',
			'express',
			'django',
			'flask',
			'lambda',
			'openwhisk-port',
		],
		Docusaurus: ['doc1', 'doc2', 'doc3'],
		Features: ['mdx'],
	},
};
