module.exports = {
	someSidebar: {
		Introduction: ['welcome', 'account'],
		'Nimbella Project': [
			'deployer-overview',
			'projects',
			'namespaces',
			'actions',
			'configuration',
			'building',
			'deployer-feature',
			'single-action',
			'namespace-to-projects',
			'deployer-specification',
		],
		'Serverless SDK': ['file-stores'],
		'Runtime & Languages': [],
		CLI: ['install', 'commands', 'flags', 'command-summary', 'wsk'],
		Workbench: [
			'workbench',
			'workbench-activations',
			'workbench-deploy-from-github',
			'workbench-playground-introduction',
			'workbench-playground-exports',
		],
		'Getting Started': ['nim-creating-project'],
		'Developing and Deploying Serverless APIs': [
			'sample-project-walkthrough',
			'basic-kv-commands',
			'deploy-from-github',
		],
		'Developing & Deploying Web': ['web-content'],
		'Taking your application to production': [],
		Integrations: [],
		'Porting existing applications onto Nimbella': [],
		Docusaurus: [],
		Features: [],
	},
};
